language: python
python:
  - "3.4"
# command to install dependencies
install:
  - "easy_install --upgrade setuptools"
  - "pip install -r requirements.txt"
  - "pip install -e ."
# command to run tests
script:
  - make test
